services:
  web:
    build: .
    container_name: fast-rabbit-vpn-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - /usr/local/etc/xray/config.json:/usr/local/etc/xray/config.json


  db:
    image: postgres:15
    container_name: fast-rabbit-vpn-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: